import { Game } from './game';

export const GAMES: Game[] = [
  { id: 1, name: 'The Last of Us Part II', description: 'Five years after their dangerous journey across the post-pandemic United States, Ellie and Joel have settled down in Jackson, Wyoming. Living amongst a thriving community of survivors has allowed them peace and stability, despite the constant threat of the infected and other, more desperate survivors. When a violent event disrupts that peace, Ellie embarks on a relentless journey to carry out justice and find closure. As she hunts those responsible one by one, she is confronted with the devastating physical and emotional repercussions of her actions.' },
  { id: 2, name: 'God of War', description: 'Kratos is a father again. As mentor and protector to Atreus, a son determined to earn his respect, he is forced to deal with and control the rage that has long defined him while out in a very dangerous world with his son. His vengeance against the Gods of Olympus behind him, Kratos now lives in the realm of Norse deities and monsters. It’s in this harsh, unforgiving world that he must fight to survive, and not only teach his son to do the same… but also prevent him from repeating the Ghost of Sparta’s bloodstained mistakes. This staggering reimagining of God of War combines all the hallmarks of the iconic series – brutal combat, epic boss fights, and breathtaking scale – and fuses them with a powerful and moving narrative that re-establishes Kratos’ world.' },
  { id: 3, name: 'Life is Strange: True Colors', description: 'Deep in the mountains of Colorado, you will find Haven Springs, a small mining town filled with beauty and mystery. As Alex, you will discover the shocking secrets behind your brother’s death in an emotional roller-coaster of an adventure, using your psychic power of Empathy to change fate and change lives.' },
  { id: 4, name: 'Uncharted', description: 'From the groundbreaking team at Naughty Dog, experience Nathan Drake’s perilous journeys across the globe, from his humble beginnings to extraordinary discoveries. Meet an unforgettable cast of characters along the way as Nathan puts his life on the line in a race against ruthless enemies to uncover unimaginable treasures.' },
  { id: 5, name: 'Final Fantasy 7: Remake', description: 'A modern reimagining of one of the most iconic games of all time, Final Fantasy VII Remake harnesses the very latest technology to recreate and expand Square Enixs legendary RPG adventure for the current generation. Set in a post-industrial fantasy world that has fallen under the control of the shadowy Shinra Electric Power Company, take on the role of Cloud Strife - a mercenary and former member of Shinras elite SOLDIER unit - and team up with anti-Shinra organization Avalanche as they step-up their resistance. Visit one of gamings most-beloved worlds with a level of depth and detail only possible in the modern age. Connect with unforgettable characters, engage in incredible battles, and experience a story that captivated a generation.' },
  { id: 6, name: 'Animal Crossing: New Horizons', description: 'Escape to a deserted island and create your own paradise as you explore, create, and customize in the Animal Crossing: New Horizons game. Your island getaway has a wealth of natural resources that can be used to craft everything from tools to creature comforts. You can hunt down insects at the crack of dawn, decorate your paradise throughout the day, or enjoy sunset on the beach while fishing in the ocean. The time of day and season match real life, so each day on your island is a chance to check in and find new surprises all year round. Show off your island utopia to family and friends—or pack your bags and visit theirs. Whether playing online* or with others beside you**, island living is even better when you can share it. Even without hopping on a flight, you’ll meet a cast of charming animal residents bursting with personality. Friendly faces like Tom Nook and Isabelle will lend their services and happily help you grow your budding community. Escape to your island getaway—however, whenever, and wherever you want.'}
];
